name: CustomBank
version: 1.0.0
main: gersom.CustomBank
api-version: 1.17
author: Gersom
softdepend: [Vault]

commands:
  bank:
    description: Custom Bank command
    aliases: [custombank]
    usage: /<command> [subcommand]
    permission-message: ยง4You don't have permission to use this command
    subcommands:
      withdraw:
        description: Withdraw money from the player
        usage: /<command> withdraw <amount>
        permission: the-skeleton-bosses.use
      balance:
        description: Shows the balance of the player
        usage: /<command> balance
        permission: the-skeleton-bosses.use
      ranking:
        description: Shows the ranking of the player
        usage: /<command> ranking
        permission: the-skeleton-bosses.use
      author:
        description: Shows author of plugin
        usage: /<command> author
        permission: the-skeleton-bosses.use

      givemoney:
        description: Gives money to the player
        usage: /<command> give <amount>
      setmoney:
        description: Sets the money of the player
        usage: /<command> setmoney <amount>
      reducemoney:
        description: Reduces the money of the player
        usage: /<command> reducemoney <amount>
      reload:
        description: Reloads config.yml
        usage: /<command> reload
        permission: the-skeleton-bosses.admin
      version:
        description: Shows version of plugin
        usage: /<command> version
        permission: the-skeleton-bosses.admin
      help:
        description: Shows help message
        usage: /<command> help
        permission: the-skeleton-bosses.admin

permissions:
  custombank.use:
    description: Allows players to use basic CustomBank commands (author)
    default: true
  custombank.admin:
    description: Allows administrators to use all CustomBank commands
    default: op
    children:
      custombank.use: true